version: "3"
networks:
  default:
services:
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    networks:
      - default
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: local_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -w test"]
      interval: 5s
      timeout: 5s
      retries: 5
  sut:
    build:
      dockerfile: Dockerfile
      context: .
    image: ansible_runserver:latest
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - '8000:8000'
    command: >
      /bin/bash -lc 'apt-get update && apt-get install -y -q --no-install-recommends netcat;
      while ! nc -z postgres 5432; do sleep 1; done;
      find . -type f -wholename "*migrations/*.py" -not -name "__init__.py" -delete;
      ./manage.py makemigrations && ./manage.py migrate;
      ./manage.py test'
    environment:
      DJANGO_SETTINGS_MODULE: ansible_runserver.settings.test
    volumes:
      - ./ansible_runserver/settings:/srv/ansible_runserver/settings
volumes:
  ansiblesite:
